self.addEventListener('install', function(event) {
    event.waitUntil(
      caches.open('cache').then(function(cache) {
        return cache.addAll([
            "/",
            "/index.html",
            "/style.css",
            "/script.js",
            "/data/underlords.json",
            "/android-chrome-192x192.png",
            "/android-chrome-512x512.png",
            "/favicon.ico",
            "/images/arrow_upward-24px.svg",
            "/images/synergies/Assassin.png",
            "/images/synergies/Brawny.png",
            "/images/synergies/Brute.png",
            "/images/synergies/Champion.png",
            "/images/synergies/Demon.png",
            "/images/synergies/Dragon.png",
            "/images/synergies/Elusive.png",
            "/images/synergies/Fallen.png",
            "/images/synergies/Healer.png",
            "/images/synergies/Heartless.png",
            "/images/synergies/Human.png",
            "/images/synergies/Hunter.png",
            "/images/synergies/Knight.png",
            "/images/synergies/Mage.png",
            "/images/synergies/Magus.png",
            "/images/synergies/Poisoner.png",
            "/images/synergies/Rogue.png",
            "/images/synergies/Savage.png",
            "/images/synergies/Scaled.png",
            "/images/synergies/Shaman.png",
            "/images/synergies/Spirit.png",
            "/images/synergies/Summoner.png",
            "/images/synergies/Swordsman.png",
            "/images/synergies/Troll.png",
            "/images/synergies/Vigilant.png",
            "/images/synergies/Void.png",
            "/images/synergies/Warrior.png",
            "/images/heroes/Abaddon_portrait_icon.png",
            "/images/heroes/Alchemist_portrait_icon.png",
            "/images/heroes/Anti-Mage_portrait_icon.png",
            "/images/heroes/Axe_portrait_icon.png",
            "/images/heroes/Batrider_portrait_icon.png",
            "/images/heroes/Beastmaster_portrait_icon.png",
            "/images/heroes/Bounty_Hunter_portrait_icon.png",
            "/images/heroes/Bristleback_portrait_icon.png",
            "/images/heroes/Chaos_Knight_portrait_icon.png",
            "/images/heroes/Crystal_Maiden_portrait_icon.png",
            "/images/heroes/Dazzle_portrait_icon.png",
            "/images/heroes/Death_Prophet_portrait_icon.png",
            "/images/heroes/Doom_portrait_icon.png",
            "/images/heroes/Dragon_Knight_portrait_icon.png",
            "/images/heroes/Drow_Ranger_portrait_icon.png",
            "/images/heroes/Earth_Spirit_portrait_icon.png",
            "/images/heroes/Ember_Spirit_portrait_icon.png",
            "/images/heroes/Enchantress_portrait_icon.png",
            "/images/heroes/Faceless_Void_portrait_icon.png",
            "/images/heroes/Juggernaut_portrait_icon.png",
            "/images/heroes/Keeper_of_the_Light_portrait_icon.png",
            "/images/heroes/Kunkka_portrait_icon.png",
            "/images/heroes/Legion_Commander_portrait_icon.png",
            "/images/heroes/Lich_portrait_icon.png",
            "/images/heroes/Lifestealer_portrait_icon.png",
            "/images/heroes/Lina_portrait_icon.png",
            "/images/heroes/Lone_Druid_portrait_icon.png",
            "/images/heroes/Luna_portrait_icon.png",
            "/images/heroes/Lycan_portrait_icon.png",
            "/images/heroes/Magnus_portrait_icon.png",
            "/images/heroes/Medusa_portrait_icon.png",
            "/images/heroes/Meepo_portrait_icon.png",
            "/images/heroes/Mirana_portrait_icon.png",
            "/images/heroes/Natures_Prophet_portrait_icon.png",
            "/images/heroes/Omniknight_portrait_icon.png",
            "/images/heroes/Pangolier_portrait_icon.png",
            "/images/heroes/Phantom_Assassin_portrait_icon.png",
            "/images/heroes/Puck_portrait_icon.png",
            "/images/heroes/Pudge_portrait_icon.png",
            "/images/heroes/Queen_of_Pain_portrait_icon.png",
            "/images/heroes/Rubick_portrait_icon.png",
            "/images/heroes/Shadow_Demon_portrait_icon.png",
            "/images/heroes/Shadow_Shaman_portrait_icon.png",
            "/images/heroes/Slardar_portrait_icon.png",
            "/images/heroes/Slark_portrait_icon.png",
            "/images/heroes/Snapfire_portrait_icon.png",
            "/images/heroes/Spectre_portrait_icon.png",
            "/images/heroes/Spirit_Breaker_portrait_icon.png",
            "/images/heroes/Storm_Spirit_portrait_icon.png",
            "/images/heroes/Sven_portrait_icon.png",
            "/images/heroes/Templar_Assassin_portrait_icon.png",
            "/images/heroes/Terrorblade_portrait_icon.png",
            "/images/heroes/Tidehunter_portrait_icon.png",
            "/images/heroes/Treant_Protector_portrait_icon.png",
            "/images/heroes/Troll_Warlord_portrait_icon.png",
            "/images/heroes/Tusk_portrait_icon.png",
            "/images/heroes/Vengeful_Spirit_portrait_icon.png",
            "/images/heroes/Venomancer_portrait_icon.png",
            "/images/heroes/Viper_portrait_icon.png",
            "/images/heroes/Void_Spirit_portrait_icon.png",
            "/images/heroes/Windranger_portrait_icon.png",
            "/images/heroes/Wraith_King_portrait_icon.png",
         ]);
      })
     );
  });


  self.addEventListener('fetch', function(event) {
    event.respondWith(async function() {
       try{
         var res = await fetch(event.request);
         var cache = await caches.open('cache');
         cache.put(event.request.url, res.clone());
         return res;
       }
       catch(error){
         return caches.match(event.request);
        }
      }());
  });
